### ISSUE TITLE
401 on image

### ISSUE THREAD

**Issue by moonmeister** [gatsbyjs/gatsby-source-wordpress-experimental#16]
When sourcing form a site with Basic credentials I'm getting 401 unauthorized on 1 image then the dev server panics out. I'm wondering if the get request isn't being passed the basic auth credentials.

**Comment by Nazeh** [comment]
Same here!
To reproduce, here is the only change on the recomended starter;

gatsby-config.js
```
...
    {
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: process.env.WPGRAPHQL_URL,
        verbose: true,
...
        auth: {
          htaccess: {
            username: process.env.HTTPBASICAUTH_USERNAME,
            password: process.env.HTTPBASICAUTH_PASSWORD,
          },
        },
...
```

Error while running `gatsby develop` or `gatsby build` with or without `gatsby clean` :

``` 
info  gatsby-source-wordpress  Unrecoverable error occured while
 fetching media item #42

Media item link: http://gatsby-wp-demo.flywheelsites.com/element
or-17/single-stroke-ar-nazeh-2/

 ERROR 

failed to process http://gatsby-wp-demo.flywheelsites.com/wp-content/uploads/2020/06/single-stroke-ar-nazeh-2.png
HTTPError: Response code 401 (Restricted)
```

**Comment by muhzulzidan** [comment]
I have experienced this a few times, and I solved it by talking to the hosting provider about the firewall that they may have set up, and the second one is when I use Cloudflare

**Comment by rodrigo-arias** [comment]
Same error here. Image fetch fails with password protect in WP Engine

![image](https://user-images.githubusercontent.com/11416255/86141677-b6b8a080-bac8-11ea-8c1f-6180960be90c.png)

**Comment by TylerBarnes** [comment]
This is fixed in `gatsby-source-wordpress-experimental@0.8.3`! Thanks for the report

**Comment by rodrigo-arias** [comment]
Tested and working now. Thanks to you!

**Comment by BadGoat** [comment]
It seems this issue is back in newer versions. Using any version up until `1.2.0` (including) - no problem. Using version `1.2.1` and above it return a 401 when trying to fetch a MediaItems from the server (WPEngine in my case):

```
failed to process https://afhl.wpengine.com/wp-content/uploads/2020/07/blogBcg.jpeg
HTTPError: Response code 401 (Unauthorized)
```

Any thoughts on this?

**Comment by rodrigo-arias** [comment]
Yesterday I updated the plugin and got this error a few times, it was somewhat inconsistent. Finally I didn't report it because it seems to have disappeared but I'm not entirely sure. I also use WP Engine.

**Comment by TylerBarnes** [comment]
Ahh, 🤔 you know there was a release recently which changes things to only add the auth headers if the domain for the request is the same as the domain of the file request. I think I know what's going on here and should have a fix for this shortly

**Comment by TylerBarnes** [comment]
I released a bug fix in `gatsby-source-wordpress-experimental@1.2.7`. Sorry for this regression! I have it near the top of my todolist to write comprehensive int tests for images & images in html. The current tests are lacking here. Closing this but please let me know if you run into other problems! I manually tested this using htpass on WPEngine and it looked like it works great 👍

**Comment by Nazeh** [comment]
Worked like a charm, finally, I can actually test how much work would this be :)

**Comment by BadGoat** [comment]
Yep, seems to work now. Thanks @TylerBarnes!
